Repository nanoframework/nanoFramework.Device.Bluetooth, pull requests merged in 2022-09, with the labels that each got.

#41 Changes to allow scanning and connections to work together
  README.md
  nanoFramework.Device.Bluetooth/BluetoothLEAdvertisementWatcher.cs
  nanoFramework.Device.Bluetooth/BluetoothLEDevice.cs
  nanoFramework.Device.Bluetooth/BluetoothNanoDevice.cs
  nanoFramework.Device.Bluetooth/GenericAttributeProfile/GattServiceProvider.cs
  nanoFramework.Device.Bluetooth/Properties/AssemblyInfo.cs
Labels: invalid

#38 Enable the Connected Event to Fire
  nanoFramework.Device.Bluetooth/BluetoothLEDevice.cs
Labels: Status: under review, Type: bug

#46 Adding Chinese version of README
  README.md
  README.zh-cn.md
Labels: Type: Documentation
